name: dev

on:
  push:
    branches: [develop]
    paths: ['terraform/**']
  workflow_dispatch:

concurrency:
  group: terraform-dev
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      apply: true
    permissions:
      contents: read
      id-token: write
    secrets: inherit
