name: main

on:
  push:
    branches: [main]
    paths: ['terraform/**']
  pull_request:
    paths: ['terraform/**']
  workflow_dispatch:

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  dev:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      apply: false
    permissions:
      contents: read
      id-token: write
    secrets: inherit

  prod:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      apply: false
    permissions:
      contents: read
      id-token: write
    secrets: inherit
