name: prod

on:
  push:
    branches: [main]
    paths: ['terraform/**']
  workflow_dispatch:

concurrency:
  group: terraform-prod
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      apply: true
    permissions:
      contents: read
      id-token: write
    secrets: inherit
